### ISSUE TITLE
[RFC] Add support for an option .mobytags file

### ISSUE THREAD

**Issue by rn** [moby/tool#101]
In linuxkit we have a whole bunch of YAML files which all need updating when hashes/tags change. It would be nice if there's only a few places which need updating. The proposal would be to add support for a `.mobytags` file which contains an entry per line specifying the tag for a given image. The `moby` tool would then look in the current directory and the user $HOME  for the file and merge the tags into the YAML file before pulling. A command line option to explicitly specify the file would also be useful.

That way we can maintain one file in the top level of the `linuxkit` repository and maybe another in `examples` while things like the tests can just use the top-level file.

**Comment by riyazdf** [comment]
👍 this sounds helpful.  We have a `$HOME/.moby` cache dir - maybe the tool can look there instead of `$HOME`?

We'd also need to make sure that the YAML merging happens before the notary lookup step, since notary will translate the tag to a digest after verifying signatures, though I think the way you describe this working should be perfectly fine.

**Comment by justincormack** [comment]
This seems to overlap with #96 a bit

**Comment by rn** [comment]
we already have this to some extend today where we concatenate files etc. and there are more proposals for compositions. So already we do not have a single source of truth.

There is a proposal to store the fully resolved YAML (or JSON) file somewhere in the artifact (https://github.com/linuxkit/linuxkit/issues/1231) and we could also output this as part of the the build and that would allow you to spot the difference

**Comment by deitch** [comment]
> There is a proposal to store the fully resolved YAML (or JSON) file somewhere in the artifact 

OK, thanks @rn

**Comment by dave-tucker** [comment]
I've been thinking about this proposal and Iit feels quite similar to #96 in it's original form...
It was originally a seperate file called `overrides.yml` with the following format.

```
- source: 
  destination: 
```

I then changed this based on review comments to be an extension of the base YAML format.

It sounds like `.mobytags` could be similar but perhaps it uses the image name as the key and offers `org`, `repo`, `tag` things that can be changed.

For example:
```
linuxkit/getty:
  tag: 0123456789deadbeef
linuxkit/sshd:
  org: davetucker
  repo: sshd
  tag: dev
```

This would serve the original use case of this PR, being able to have a `.mobytags` file checked in and be a single point of entry to update package hashes across the repo.

It would also solve the CI use case as CI could generate a temporary `.mobytags` file to change the org to `linuxkitci` and the `tag` to the new hash in order to test unreleased packages before push/sign.

It would also mean that you could add your local test image to `.mobytags` and it would be used in all the tests (as in the above example). That's quite a win in my book.

**Comment by dave-tucker** [comment]
Oh, and it also cleanly separates the use cases of tag overwriting and composition of moby files

**Comment by deitch** [comment]
@dave-tucker so my `.yml` file would have just the `image: linuxkit/foo` (or even `linuxkit/foo:abcd6554`), and the "override" file would cause it to be overridden, anyplace that there is an image "match"? And it could match `namespace/repo:tag`, `namespace/repo` or just `namespace`, and replace just `namespace` (leaving tag+hash alone), `namespace/tag` or `namespace/tag:hash`?

Is that easier than the other proposal to have a composition:

```
moby build -f base.yml -f specifics.yml
```

Where `base.yml` might have my kernel and some init and onboot and services, and `specifics.yml` has just the difference.

Then again, I think they are 2 different use cases. The latter really solves more of the composition issue. This `.mobytags` solves more the "I want to use this set of compositions but override certain images", useful for local development/testing, and for CI

**Comment by dave-tucker** [comment]
> so my .yml file would have just the image: linuxkit/foo (or even linuxkit/foo:abcd6554), and the "override" file would cause it to be overridden, anyplace that there is an image "match"? And it could match namespace/repo:tag, namespace/repo or just namespace, and replace just namespace (leaving tag+hash alone), namespace/tag or namespace/tag:hash?

Let's call `override`, `.mobytags` but otherwise yes that's exactly what I'm proposing.

I think we should be clear that this isn't a mechanism for composition but it's a helpful way of managing hashes across yaml files.

**Comment by deitch** [comment]
> this isn't a mechanism for composition but it's a helpful way of managing hashes across yaml files.

Got it. So they are complementary. Sounds good.

**Comment by dave-tucker** [comment]
> So they are complementary

Yes, I'd envisage `.mobytags` being evaluated *after* composition in order for this to work correctly

**Comment by deitch** [comment]
The more I think about it, the more like it.

* composition merges multiple files to get a unified build config
* `mobytags` overrides any images matching certain rules in the unified build config, independent of section `kernel` vs `onboot` vs `init` vs `services` vs etc.

The two suggestion I would have are:

1. put the overrides in a key in the yml file, since we might override some other things later (`files`? who knows?)
2. Call it something other than `mobytags` since we might override some other things later

Sort of 

```yml
images:
  linuxkit/getty:
    tag: 0123456789deadbeef
  linuxkit/sshd:
    org: davetucker
    repo: sshd
    tag: dev
```

**Comment by justincormack** [comment]
We should work on doing this in linuxkit...
